### ISSUE TITLE
The node_modules dist dir doesn't exist

### ISSUE THREAD

**Issue by nedkelly** [cherryblossom000/typedoc-plugin-param-names#1]
Running `yarn add typedoc-plugin-param-names -WD` installs the module but the folder contains only the CHANGELOG, LICENSE, README.md and package.json, there is no `dist` directory.

```bash
Loaded plugin /home/****/****/****/****/node_modules/typedoc-plugin-external-module-map
Loaded plugin /home/****/****/****/****/node_modules/typedoc-plugin-lerna-packages
Error: The plugin /home/****/****/****/****/node_modules/typedoc-plugin-param-names could not be loaded.

Error: Cannot find module '/home/****/****/****/****/node_modules/typedoc-plugin-param-names/dist/index'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:322:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:683:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:953:27)
    at Function.Module._load (internal/modules/cjs/loader.js:842:27)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at PluginHost.load (/home/****/****/****/****/node_modules/typedoc/dist/lib/utils/plugins.js:23:34)
    at CliApplication.bootstrap (/home/****/****/****/****/node_modules/typedoc/dist/lib/application.js:50:22)
    at CliApplication.bootstrap (/home/****/****/****/****/node_modules/typedoc/dist/lib/cli.js:29:30)
    at Object.<anonymous> (/home/****/****/****/****/node_modules/typedoc/bin/typedoc:5:5)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by nedkelly** [comment]
Looks like `tsc` is required:
```bash
/bin/sh: 1: tsc: not found
```
Might be worth documenting this.
👍

**Comment by cherryblossom000** [comment]
Sorry about that! I'm not sure why the `dist` folder doesn't get released during the CI: I'll investigate that. I've released v1.0.2, which includes the `dist` directory and should work. (I tried releasing v1.0.1 during the CI but that didn't work, so I unpublished v1.0.1.)

**Comment by cherryblossom000** [comment]
I've fixed the CI. The issue was that it was downloading the *contents* of `dist` to the root directory, instead of downloading `dist` into a new `dist` folder.

Sorry again for not testing if my package actually worked.

**Comment by nedkelly** [comment]
Thanks for the quick fix
